{% set name = "hazm" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: be52ad5c46c09186ebeaf6169f1638afceb4f9330211fd0dacd25736a6ac3d7c

build:
  skip: true  # [win]
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - libwapiti >=0.2.1
    - nltk >=3.3
    - python >=3.6

test:
  imports:
    - hazm

about:
  home: http://www.sobhe.ir/hazm/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python library for digesting Persian text.
  doc_url: https://github.com/sobhe/hazm
  dev_url: https://github.com/sobhe/hazm

extra:
  recipe-maintainers:
    - monaldoj
