travis:
  secure:
    BINSTAR_TOKEN: VXTQTscbQ6iikGdb6wN8USSPGMrbSeVU3KNwUdWzo83KVXWd63x6Vy5OERwcS9YKPObIs+A1U9qkt1qea76fEQRuxFcMBfiR7NBXK3/qvkHmGa95orQKGyw1ZHvBmdA3jrxw7ifB1JbSSann1Z+TduHBeycrV0P7ZdBkrjo9mYy8AA+qU54WD7/w5HmnV5SIVxkbISMM2runKV9X+gRxAU9uXKz0D3S+qePgw06VRBbaX5j50qM99T2Mvf4G4VTDhOKazVxqk02QiOtO868qVggvbfvZ/k2jJMn3JLBiK95kf6UItTUdlIolDZ/aiRJ5YF807myzGb84ea5gU8nQaPpUU53CiRuOEX+tni+AFMAHNMke6SaXlSWl4iLq2bjO4y30Wg3L4CJ+9rMzlIAWjyjCOiptkAaExSMCmh0chBdBlb5rZSjaUSA7b0W2H2Jn0rLl0LQtICBWlv2wdfkTeY7iONPTSQ73L/Qtpo95nqPDPH6YbGIgb+ES5WTqfMqA9UD30KKenY5igEryQPdcHr3hf8JIVEDBNMCJ/6Ssb+TZgVUuqLcm3fSZLtSkfsHN51V/EvgP5O4Dh7XJz1AmyTikW6qNenyw4pEQQEb1uzQs1xXk2QGgOsq36HnRH9g6ckmDmw5bJGDxniTA2Ju6/R/hGFG1CNkcSh5FIAjl9cQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
